[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.0"
console_error_panic_hook = "0.1"
bevy-inspector-egui = "0.18.3"

[dependencies.bevy]
version = "0.10"
features = [
    "bmp",
    "wav"
]

[profile.release]
opt-level = 's'
lto = "thin"
